"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import dynamic from "next/dynamic";
import { ArrowDown,ArrowLeft,ArrowRight,ArrowUp,ArrowUpRight,Armchair,Bath,BedDouble,Bookmark,Box,Check,ChevronLeft,ChevronRight,Copy,DoorOpen,Download,Expand,Eye,EyeOff,Footprints,Grid2X2,House,Layers3,LayoutDashboard,LoaderCircle,Maximize2,Minus,Moon,MousePointer2,Move,Pause,Play,Plus,Redo2,Rotate3D,RotateCcw,RotateCw,Ruler,Scan,Shrink,Sofa,Sun,Sunset,Trash2,Undo2,UtensilsCrossed,X } from "lucide-react";
import { Slider } from "@/components/ui/slider";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { Switch } from "@/components/ui/switch";
import { Toaster } from "@/components/ui/sonner";
import { toast } from "sonner";
import { apartments,palettes,floors,createDesigns,validDesigns,roomArea,defaultTransform,type Apartment,type Designs,type ObjectInfo,type Finish } from "./apartment-data";
import type { ApartmentApi } from "./apartment-scene";
const Scene=dynamic(()=>import("./apartment-scene"),{ssr:false,loading:()=> <div className="scene-loading"><LoaderCircle className="loading-spin" size={25}/><span>Открываем квартиру…</span></div>});
const icons={living:Sofa,kitchen:UtensilsCrossed,bedroom:BedDouble,office:Armchair,nursery:BedDouble,bath:Bath,hall:DoorOpen};
const stages=[{name:"Основа",at:0},{name:"Отделка",at:40},{name:"Мебель",at:75},{name:"Детали",at:100}];
type Saved={id:string;name:string;apartmentId:string;designs:Designs;lighting:string;date:string};
function MiniPlan({apartment,active,onSelect,compact=false}:{apartment:Apartment;active?:string|null;onSelect?:(id:string)=>void;compact?:boolean}){
 return <svg viewBox={`-.2 -.2 ${apartment.w+.4} ${apartment.d+.4}`} className={compact?"plan-mini":"plan-map"} aria-hidden={onSelect?undefined:true} role={onSelect?"group":undefined} aria-label={onSelect?"План квартиры. Выберите комнату":undefined}>{apartment.rooms.map((r,i)=><g key={r.id} role={onSelect?"button":undefined} tabIndex={onSelect?0:undefined} aria-label={onSelect?`${r.name}, ${roomArea(r)} м²`:undefined} aria-pressed={onSelect?active===r.id:undefined} onClick={()=>onSelect?.(r.id)} onKeyDown={e=>{if(onSelect&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onSelect(r.id);}}}><rect x={r.x+.065} y={r.z+.065} width={r.w-.13} height={r.d-.13} rx=".06" fill={active===r.id?"#8d9f7d":r.kind==="bath"?"#d6dfdd":r.kind==="hall"?"#e5e3d8":i%2?"#d4c9b9":"#d9ddcc"} stroke={active===r.id?"#5c744f":"#f8f8ef"} strokeWidth=".055"/>{!compact&&<text x={r.x+r.w/2} y={r.z+r.d/2+.13} textAnchor="middle" fontSize={r.kind==="hall"?".3":".37"} fill={active===r.id?"#fffdf3":"#506047"}>{i+1}</text>}</g>)}</svg>;
}

export default function Studio(){
 const [apartmentId,setApartmentId]=useState("balance"),[history,setHistory]=useState<{past:Designs[];present:Designs;future:Designs[]}>({past:[],present:createDesigns(),future:[]});
 const designs=history.present,apartment=apartments.find(a=>a.id===apartmentId)!,design=designs[apartmentId];
 const [roomId,setRoomId]=useState<string|null>(null),[object,setObject]=useState<ObjectInfo|null>(null),[view,setView]=useState("dollhouse"),[lighting,setLighting]=useState("day"),[tab,setTab]=useState("rooms");
 const [progress,setProgress]=useState(100),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[compare,setCompare]=useState(false),[tour,setTour]=useState(false),[scrollMode,setScrollMode]=useState(false);
 const [zoom,setZoom]=useState(1),[reset,setReset]=useState(0),[rotate,setRotate]=useState(false),[fullWalls,setFullWalls]=useState(false),[doors,setDoors]=useState(true),[furniture,setFurniture]=useState(true),[isolate,setIsolate]=useState(false),[labels,setLabels]=useState(true),[dimensions,setDimensions]=useState(false);
 const [catalog,setCatalog]=useState<ObjectInfo[]>([]);
 const [ready,setReady]=useState(false),[fullscreen,setFullscreen]=useState(false),[reduced,setReduced]=useState(false),[saved,setSaved]=useState<Saved[]>([]),[exporting,setExporting]=useState(false),[exportUrl,setExportUrl]=useState<string|null>(null),[showSaved,setShowSaved]=useState(false);
 const section=useRef<HTMLElement>(null),workspace=useRef<HTMLDivElement>(null),api=useRef<ApartmentApi|null>(null),progressRef=useRef(progress);progressRef.current=progress;
 const room=apartment.rooms.find(r=>r.id===roomId),finish=room?design.rooms[room.id]:design.rooms[apartment.rooms[0].id],activeStage=progress<20?0:progress<52?1:progress<84?2:3;
 const edit=useCallback((update:(d:Designs)=>Designs)=>setHistory(h=>({past:[...h.past.slice(-24),h.present],present:update(h.present),future:[]})),[]);
 function undo(){setHistory(h=>h.past.length?{past:h.past.slice(0,-1),present:h.past.at(-1)!,future:[h.present,...h.future]}:h);}
 function redo(){setHistory(h=>h.future.length?{past:[...h.past,h.present],present:h.future[0],future:h.future.slice(1)}:h);}
 function selectRoom(id:string|null,keepTour=false){setRoomId(id);setObject(null);setZoom(1);setRotate(false);if(!keepTour)setTour(false);if(!id){setView("dollhouse");setIsolate(false);}setReset(n=>n+1);}
 function changeApartment(id:string){if(id===apartmentId)return;setApartmentId(id);selectRoom(null);setReady(false);setCatalog([]);api.current=null;setProgress(100);setPlaying(false);setCompare(false);setScrollMode(false);setExportUrl(null);setTab("rooms");}
 function changeFinish(key:keyof Finish,value:string){edit(all=>{const next=structuredClone(all);for(const r of apartment.rooms)if(!roomId||r.id===roomId)next[apartmentId].rooms[r.id][key]=value;return next;});}
 function applyToAll(){edit(all=>{const next=structuredClone(all);for(const r of apartment.rooms)next[apartmentId].rooms[r.id]={...finish};return next;});toast.success("Палитра и пол применены ко всей квартире");}
 function selectObject(info:ObjectInfo|null){setObject(info);if(info){setRoomId(info.roomId);setTab("objects");setTour(false);setRotate(false);}}
 function transformObject(action:"left"|"right"|"up"|"down"|"rotate"|"hide"|"reset"){
  if(!object)return;const r=apartment.rooms.find(r=>r.id===object.roomId)!;
  if(action==="rotate"){const rotation=(design.objects[object.id]?.rotation||0)+90,angle=object.rotation+rotation*Math.PI/180,w=Math.abs(Math.cos(angle))*object.w+Math.abs(Math.sin(angle))*object.d,d=Math.abs(Math.sin(angle))*object.w+Math.abs(Math.cos(angle))*object.d;if(w>r.w-.1||d>r.d-.1){toast.info("Для такого поворота в комнате мало места");return;}}
  edit(all=>{const next=structuredClone(all),t={...(next[apartmentId].objects[object.id]||defaultTransform)};
   if(action==="reset")next[apartmentId].objects[object.id]={...defaultTransform};else{
    if(action==="rotate")t.rotation=(t.rotation+90)%360;if(action==="hide")t.hidden=!t.hidden;
    if(action==="left")t.dx-=.2;if(action==="right")t.dx+=.2;if(action==="up")t.dz-=.2;if(action==="down")t.dz+=.2;
    const angle=object.rotation+t.rotation*Math.PI/180,w=Math.abs(Math.cos(angle))*object.w+Math.abs(Math.sin(angle))*object.d,d=Math.abs(Math.sin(angle))*object.w+Math.abs(Math.cos(angle))*object.d;
    const minX=-r.w/2+w/2+.05,maxX=r.w/2-w/2-.05,minZ=-r.d/2+d/2+.05,maxZ=r.d/2-d/2-.05;
    if(minX<=maxX)t.dx=Math.max(minX,Math.min(maxX,object.x+t.dx))-object.x;if(minZ<=maxZ)t.dz=Math.max(minZ,Math.min(maxZ,object.z+t.dz))-object.z;
    next[apartmentId].objects[object.id]=t;
   }return next;
  });
 }
 function setStage(v:number){setScrollMode(false);setPlaying(false);setCompare(false);setProgress(v);}
 function play(){setScrollMode(false);setCompare(false);setTour(false);if(playing){setPlaying(false);return;}if(progress>=99)setProgress(0);setPlaying(true);}
 function startTour(){if(tour){setTour(false);return;}setScrollMode(false);setPlaying(false);setProgress(100);setCompare(false);setIsolate(false);selectRoom(apartment.rooms[0].id,true);setView("walk");setTour(true);}
 function nextRoom(direction:number){const index=apartment.rooms.findIndex(r=>r.id===roomId),next=(index+direction+apartment.rooms.length)%apartment.rooms.length;selectRoom(apartment.rooms[next].id);}
 useEffect(()=>{
  try{const raw=JSON.parse(localStorage.getItem("gasgarick-apartments-v3")||"[]");if(Array.isArray(raw))setSaved(raw.filter(s=>s&&typeof s.name==="string"&&typeof s.id==="string"&&typeof s.date==="string"&&apartments.some(a=>a.id===s.apartmentId)&&validDesigns(s.designs)).slice(0,4));}catch{}
  const mq=matchMedia("(prefers-reduced-motion: reduce)"),sync=()=>{setReduced(mq.matches);if(mq.matches){setRotate(false);setTour(false);setPlaying(false);setScrollMode(false);}};sync();mq.addEventListener("change",sync);
  const full=()=>setFullscreen(document.fullscreenElement===workspace.current);document.addEventListener("fullscreenchange",full);return()=>{mq.removeEventListener("change",sync);document.removeEventListener("fullscreenchange",full);};
 },[]);
 useEffect(()=>{if(!playing)return;let frame=0,last=0,current=progressRef.current;const tick=(time:number)=>{if(!document.hidden){current=Math.min(100,current+(last?Math.min(100,time-last):0)*speed/145);setProgress(current);if(current>=100){setPlaying(false);return;}}last=time;frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing,speed]);
 useEffect(()=>{if(!tour)return;const id=setInterval(()=>{setRoomId(previous=>{const index=apartment.rooms.findIndex(r=>r.id===previous);if(index>=apartment.rooms.length-1){setTour(false);setView("dollhouse");setZoom(1);return null;}return apartment.rooms[index+1].id;});setObject(null);setReset(n=>n+1);},6500);return()=>clearInterval(id);},[tour,apartment]);
 useEffect(()=>{if(!scrollMode)return;let frame=0;const update=()=>{const el=section.current;if(!el)return;const rect=el.getBoundingClientRect();setProgress(Math.max(0,Math.min(100,(-rect.top+100)/Math.max(1,el.offsetHeight-innerHeight)*100)));};const scroll=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(update);};addEventListener("scroll",scroll,{passive:true});addEventListener("resize",scroll);update();return()=>{removeEventListener("scroll",scroll);removeEventListener("resize",scroll);cancelAnimationFrame(frame);};},[scrollMode]);
 useEffect(()=>{
  const handler=(e:KeyboardEvent)=>{if(!(e.target instanceof Element)||!section.current?.contains(e.target)||e.target.closest("input,textarea"))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==="Escape"){setObject(null);setTour(false);}};document.addEventListener("keydown",handler);return()=>document.removeEventListener("keydown",handler);
 },[]);
 // Expose the same finite configuration controls to browsers that support WebMCP.
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<object>};const context=(document as Document&{modelContext?:{registerTool:(t:Tool,o:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
  try{void Promise.resolve(context.registerTool({name:"explore_apartment",description:"Select a gasgarick sample apartment, room and camera view in the visible 3D studio.",inputSchema:{type:"object",properties:{apartment:{type:"string",enum:apartments.map(a=>a.id)},room:{type:"string"},view:{type:"string",enum:["dollhouse","plan","walk"]}},required:["apartment"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const d=input as Record<string,string>,a=apartments.find(a=>a.id===d?.apartment);if(!a||Object.keys(d).some(k=>!["apartment","room","view"].includes(k))||d.room&&!a.rooms.some(r=>r.id===d.room)||d.view&&!["dollhouse","plan","walk"].includes(d.view))throw new Error("Invalid apartment configuration");changeApartment(a.id);selectRoom(d.room||null);setView(d.view||"dollhouse");if(d.view==="walk"&&!d.room)setRoomId(a.rooms[0].id);return {apartment:a.id,room:d.room||null,view:d.view||"dollhouse"};}},{signal:life.signal})).catch(()=>{});}catch{}return()=>life.abort();
 },[apartmentId]);
 function save(){const item:Saved={id:Date.now().toString(),name:apartment.name+" · "+(saved.filter(s=>s.apartmentId===apartmentId).length+1),apartmentId,designs:structuredClone(designs),lighting,date:new Date().toLocaleDateString("ru-RU")};const next=[item,...saved].slice(0,4);try{localStorage.setItem("gasgarick-apartments-v3",JSON.stringify(next));setSaved(next);setShowSaved(true);toast.success("Вариант сохранён на этом устройстве");}catch{toast.error("Не удалось сохранить вариант");}}
 function restore(item:Saved){changeApartment(item.apartmentId);edit(()=>structuredClone(item.designs));setLighting(["day","sunset","night"].includes(item.lighting)?item.lighting:"day");setStage(100);setObject(null);toast.success("Вариант восстановлен");}
 function removeSaved(id:string){const next=saved.filter(s=>s.id!==id);try{localStorage.setItem("gasgarick-apartments-v3",JSON.stringify(next));setSaved(next);}catch{toast.error("Не удалось удалить вариант");}}
 async function snapshot(){if(!api.current)return;setExporting(true);try{const url=await api.current.snapshot();setExportUrl(url);const a=document.createElement("a");a.href=url;a.download="gasgarick-"+apartmentId+".png";a.click();toast.success("Кадр готов к скачиванию");}catch{toast.error("Не удалось сохранить кадр");}finally{setExporting(false);}}
 function exportProject(){const data={name:apartment.name,area:apartment.area,lighting,rooms:apartment.rooms.map(r=>({name:r.name,area:Math.round(r.w*r.d*100)/100,dimensions:[r.w,r.d],...design.rooms[r.id]})),furniture:design.objects,notice:"Демонстрационная концепция, не рабочий строительный чертёж"};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="gasgarick-"+apartmentId+".json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast.success("Настройки проекта скачаны");}
 async function toggleFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else if(workspace.current?.requestFullscreen)await workspace.current.requestFullscreen();else toast.info("Полный экран недоступен в этом браузере");}catch{toast.info("Браузер не разрешил открыть полный экран");}}
 const objectTransform=object?design.objects[object.id]||defaultTransform:null;
 return <section ref={section} id="studio" className={`apartment-studio ${scrollMode?"apartment-scroll-story":""}`}>
  <div className="apartment-intro"><div><span className="section-kicker">GASGARICK / ИНТЕРАКТИВНЫЕ КВАРТИРЫ</span><h1>Ваша жизнь. <em>В объёме.</em></h1></div><p>От целой квартиры — к любимой детали.<br/>Выберите пространство и обустройте его.</p></div>
  <div className="apartment-picker" aria-label="Выбор квартиры">{apartments.map((a,i)=><button key={a.id} onClick={()=>changeApartment(a.id)} aria-pressed={apartmentId===a.id} className={`apartment-card ${apartmentId===a.id?"active":""}`}><span className="apartment-number">0{i+1}</span><MiniPlan apartment={a} compact/><span className="apartment-card-copy"><strong>{a.name}</strong><small>{a.subtitle} · {a.rooms.length} помещений</small></span><span className="apartment-area">{a.area}<small>м²</small></span><span className="apartment-check">{apartmentId===a.id?<Check size={17}/>:<ArrowUpRight size={17}/>}</span></button>)}</div>
  <div className="apartment-sticky">
   <div className="apartment-toolbar"><div className="workspace-label"><span>ВАШ ПРОЕКТ</span><strong>{apartment.name}</strong><span className="concept-tag">Концепция</span></div><div className="workspace-actions"><button className="text-tool" onClick={()=>setShowSaved(!showSaved)} aria-expanded={showSaved}><Bookmark size={16}/><span>Мои варианты</span>{saved.length>0&&<small>{saved.length}</small>}</button><button className="tour-button" onClick={startTour} disabled={!ready||reduced}><Footprints size={16}/>{tour?"Остановить тур":"Прогулка по квартире"}{tour?<Pause size={15}/>:<ArrowUpRight size={15}/>}</button></div></div>
   {showSaved&&<div className="saved-shelf"><div><strong>Мои варианты</strong><span>До 4 вариантов на этом устройстве</span></div>{saved.length===0?<p>Настройте интерьер и нажмите «Сохранить».</p>:saved.map(s=><div key={s.id} className="saved-variant"><button onClick={()=>restore(s)}><strong>{s.name}</strong><small>{s.date} · {apartments.find(a=>a.id===s.apartmentId)?.area} м²</small></button><button onClick={()=>removeSaved(s.id)} aria-label={`Удалить вариант ${s.name}`}><Trash2 size={15}/></button></div>)}<button className="plain-icon shelf-close" onClick={()=>setShowSaved(false)} aria-label="Закрыть сохранённые варианты"><X size={17}/></button></div>}
   <div className="apartment-workspace" ref={workspace} data-lighting={lighting}>
    <div className="apartment-viewport">
     <div className="apartment-scene-head"><div className="scene-breadcrumb"><button onClick={()=>selectRoom(null)}><House size={15}/>Вся квартира</button>{room&&<><ChevronRight size={13}/><span>{room.name}</span></>}<small>{room?roomArea(room):apartment.area} м²</small></div><div className="head-tools"><button className="plain-icon" onClick={snapshot} disabled={!ready||exporting} aria-label="Скачать изображение" title="Скачать PNG">{exporting?<LoaderCircle size={18} className="loading-spin"/>:<Download size={18}/>}</button><button className="plain-icon" onClick={toggleFullscreen} aria-label={fullscreen?"Выйти из полного экрана":"На весь экран"} title="На весь экран">{fullscreen?<Shrink size={18}/>:<Expand size={18}/>}</button></div></div>
     <div className="apartment-scene" key={apartment.id}><Scene apartment={apartment} design={design} roomId={roomId} objectId={object?.id||null} view={view} progress={compare?0:progress} lighting={lighting} zoom={zoom} wheelZoom={!scrollMode} reset={reset} rotate={rotate} walls={fullWalls} doors={doors} furniture={furniture} isolate={isolate} labels={labels} dimensions={dimensions} onReady={value=>{api.current=value;setCatalog(value.objects);setReady(true);}} onRoom={id=>selectRoom(id)} onObject={selectObject} onDoors={()=>{setDoors(v=>!v);toast.info(doors?"Двери закрываются":"Двери открываются");}} onInteraction={()=>{setRotate(false);setTour(false);}} onZoom={factor=>{setZoom(z=>Math.max(.65,Math.min(1.8,z*factor)));setRotate(false);setTour(false);}}/></div>
     {compare&&<span className="apartment-before">До ремонта</span>}
     {tour&&<div className="tour-progress" aria-live="polite"><span className="tour-pulse"/>ПРОГУЛКА · {apartment.rooms.findIndex(r=>r.id===roomId)+1} / {apartment.rooms.length}<div key={roomId} className="tour-time"/></div>}
     <div className="apartment-side-tools"><button className={dimensions?"active":""} onClick={()=>setDimensions(!dimensions)} aria-label="Показать размеры" aria-pressed={dimensions} title="Размеры"><Ruler size={18}/></button><button className={labels?"active":""} onClick={()=>setLabels(!labels)} aria-label="Названия комнат" aria-pressed={labels} title="Названия комнат"><Grid2X2 size={18}/></button><button className={rotate?"active":""} disabled={reduced||view!=="dollhouse"} onClick={()=>setRotate(!rotate)} aria-label="Автовращение" aria-pressed={rotate} title="Автовращение"><Rotate3D size={19}/></button></div>
     {room&&<div className="scene-minimap"><div><span>ВЫ ЗДЕСЬ</span><button onClick={()=>selectRoom(null)} aria-label="Показать всю квартиру"><Maximize2 size={13}/></button></div><MiniPlan apartment={apartment} active={roomId} onSelect={id=>selectRoom(id)}/></div>}
     <div className="apartment-view-controls"><Tabs value={view} onValueChange={v=>{setView(v);setRotate(false);setTour(false);setZoom(1);if(v==="walk"&&!roomId)setRoomId(apartment.rooms[0].id);}}><TabsList aria-label="Режим просмотра квартиры"><TabsTrigger value="dollhouse"><Box size={15}/>Объём</TabsTrigger><TabsTrigger value="plan"><Scan size={15}/>План</TabsTrigger><TabsTrigger value="walk"><Eye size={15}/>Внутри</TabsTrigger></TabsList></Tabs></div>
     <div className="apartment-zoom"><button onClick={()=>setZoom(z=>Math.max(.65,z-.15))} disabled={zoom<=.65} aria-label="Отдалить"><Minus size={16}/></button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.8,z+.15))} disabled={zoom>=1.8} aria-label="Приблизить"><Plus size={16}/></button><button onClick={()=>{setZoom(1);setReset(n=>n+1);setRotate(false);}} aria-label="Сбросить ракурс"><RotateCcw size={15}/></button></div>
     <div className="apartment-scene-note"><MousePointer2 size={14}/>{scrollMode?"Прокрутка — этапы ремонта":view==="walk"?"Осмотритесь мышью · колесо — масштаб":room?"Колесо — масштаб · нажмите на предмет для расстановки":"Колесо — масштаб · тяните мышью, чтобы вращать"}</div>
    </div>
    <aside className="apartment-inspector" data-lenis-prevent aria-label="Настройки квартиры">
     <div className="inspector-title"><span>{room?"ВАША КОМНАТА":"ВСЯ КВАРТИРА"}</span><div><button className="plain-icon" onClick={undo} disabled={!history.past.length} aria-label="Отменить изменение" title="Отменить"><Undo2 size={16}/></button><button className="plain-icon" onClick={redo} disabled={!history.future.length} aria-label="Повторить изменение" title="Повторить"><Redo2 size={16}/></button></div></div>
     <div className="inspector-room"><h2>{room?.name||apartment.name}</h2><span>{room?`${roomArea(room)} м² · ${room.w.toLocaleString("ru-RU")} × ${room.d.toLocaleString("ru-RU")} м`:`${apartment.area} м² · ${apartment.rooms.length} помещений`}</span></div>
     <Tabs value={tab} onValueChange={setTab} className="inspector-tabs"><TabsList aria-label="Панель настройки"><TabsTrigger value="rooms">Комнаты</TabsTrigger><TabsTrigger value="materials">Материалы</TabsTrigger><TabsTrigger value="objects">Предметы</TabsTrigger></TabsList></Tabs>
     <div className="inspector-content" key={tab+apartment.id}>
      {tab==="rooms"&&<><div className="room-list"><button className={!room?"selected":""} onClick={()=>selectRoom(null)} aria-pressed={!room}><span className="room-list-icon"><LayoutDashboard size={18}/></span><span><strong>Вся квартира</strong><small>Общий вид</small></span><span>{apartment.area} м²</span></button>{apartment.rooms.map((r,i)=>{const Icon=icons[r.kind];return <button key={r.id} className={roomId===r.id?"selected":""} onClick={()=>selectRoom(r.id)} aria-pressed={roomId===r.id}><span className="room-list-icon"><Icon size={18}/></span><span><strong>{r.name}</strong><small>0{i+1}</small></span><span>{roomArea(r)} м²</span></button>;})}</div>{room&&<p className="room-note">{room.note}</p>}<div className="inspector-switch"><label htmlFor="isolate">Только выбранная комната</label><Switch id="isolate" checked={isolate} disabled={!room} onCheckedChange={setIsolate}/></div></>}
      {tab==="materials"&&<><div className="editing-scope">{room?<><span className="scope-dot"/>{room.name}</>:<><House size={14}/>Изменения для всей квартиры</>}</div><fieldset className="config-field"><legend>Цвет акцентов</legend><RadioGroup value={finish.palette} onValueChange={v=>changeFinish("palette",v)} aria-label="Цвет акцентов" className="color-options">{palettes.map(p=><label key={p.id} className="color-option"><RadioGroupItem value={p.id} aria-label={p.name} className="sr-only"/><span style={{background:p.color}}><Check size={17}/></span><small>{p.name}</small></label>)}</RadioGroup></fieldset><fieldset className="config-field"><legend>Материал пола</legend><RadioGroup value={finish.floor} onValueChange={v=>changeFinish("floor",v)} aria-label="Материал пола" className="floor-options">{floors.map(f=><label className="floor-option" key={f.id}><RadioGroupItem value={f.id} aria-label={f.name} className="sr-only"/><span className={`material-sample ${f.id}`} style={{backgroundColor:f.color}}/><span>{f.name}</span><Check size={14}/></label>)}</RadioGroup></fieldset>{room&&<button className="apply-all" onClick={applyToAll}><Copy size={14}/>Применить ко всей квартире</button>}<p className="subtle-note">У каждой комнаты своя палитра. Перейдите в другую, чтобы настроить её отдельно.</p></>}
      {tab==="objects"&&<><label className="object-picker"><span>Предмет в комнате</span><select aria-label="Выбор предмета" value={object?.id||""} onChange={e=>selectObject(catalog.find(o=>o.id===e.target.value)||null)}><option value="">Выберите предмет…</option>{catalog.filter(o=>!roomId||o.roomId===roomId).map(o=><option value={o.id} key={o.id}>{o.name}{!roomId?" · "+apartment.rooms.find(r=>r.id===o.roomId)?.name:""}</option>)}</select></label>{object?<div className="object-editor"><div className="object-editor-title"><span className="room-list-icon"><Move size={21}/></span><div><strong>{object.name}</strong><small>{room?.name}</small></div><button className="plain-icon" onClick={()=>setObject(null)} aria-label="Снять выбор предмета"><X size={16}/></button></div><span className="move-label">Перемещение · шаг 20 см</span><div className="object-move"><button onClick={()=>transformObject("up")} aria-label="Сдвинуть предмет назад"><ArrowUp size={18}/></button><button onClick={()=>transformObject("left")} aria-label="Сдвинуть предмет влево"><ArrowLeft size={18}/></button><span><Move size={19}/></span><button onClick={()=>transformObject("right")} aria-label="Сдвинуть предмет вправо"><ArrowRight size={18}/></button><button onClick={()=>transformObject("down")} aria-label="Сдвинуть предмет вперёд"><ArrowDown size={18}/></button></div><div className="object-actions"><button onClick={()=>transformObject("rotate")}><RotateCw size={17}/>Повернуть 90°</button><button onClick={()=>transformObject("hide")}>{objectTransform?.hidden?<Eye size={17}/>:<EyeOff size={17}/>} {objectTransform?.hidden?"Показать":"Скрыть"}</button><button onClick={()=>transformObject("reset")}><RotateCcw size={16}/>На исходное место</button></div></div>:<div className="object-empty"><Armchair size={36} strokeWidth={1}/><h3>У каждой вещи<br/>есть своё место</h3><p>Нажмите на мебель в 3D, чтобы переместить, повернуть или скрыть предмет.</p></div>}<div className="inspector-switch"><label htmlFor="furniture">Показывать мебель</label><Switch id="furniture" checked={furniture} onCheckedChange={setFurniture}/></div><div className="inspector-switch"><label htmlFor="doors">Открыть двери</label><Switch id="doors" checked={doors} onCheckedChange={setDoors}/></div><div className="inspector-switch"><label htmlFor="walls">Полная высота стен</label><Switch id="walls" checked={fullWalls} onCheckedChange={setFullWalls}/></div>{Object.values(design.objects).some(t=>t.hidden)&&<button className="apply-all" onClick={()=>edit(all=>{const n=structuredClone(all);Object.values(n[apartmentId].objects).forEach(t=>t.hidden=false);return n;})}><Eye size={14}/>Вернуть скрытые предметы</button>}</>}
     </div>
     <div className="inspector-light"><span>Свет в квартире</span><RadioGroup value={lighting} onValueChange={setLighting} aria-label="Освещение квартиры" className="apartment-light-options">{[{id:"day",name:"День",Icon:Sun},{id:"sunset",name:"Закат",Icon:Sunset},{id:"night",name:"Вечер",Icon:Moon}].map(l=><label key={l.id} title={l.name}><RadioGroupItem value={l.id} aria-label={l.name} className="sr-only"/><l.Icon size={16}/><span>{l.name}</span></label>)}</RadioGroup></div>
     <div className="inspector-save"><button onClick={save}><Bookmark size={16}/>Сохранить вариант<ArrowUpRight size={16}/></button><button className="plain-icon" onClick={exportProject} aria-label="Скачать настройки проекта" title="Скачать настройки"><Download size={17}/></button></div><span className="device-note">Сохранение на этом устройстве</span>
    </aside>
    {room&&<div className="room-navigation"><button onClick={()=>nextRoom(-1)}><ChevronLeft size={17}/><span>Предыдущая комната</span></button><span><strong>{room.name}</strong><small>{apartment.rooms.findIndex(r=>r.id===roomId)+1} / {apartment.rooms.length}</small></span><button onClick={()=>nextRoom(1)}><span>Следующая комната</span><ChevronRight size={17}/></button></div>}
    <div className="apartment-timeline"><button className="timeline-play" onClick={play} disabled={!ready||reduced} aria-label={playing?"Приостановить анимацию":"Запустить анимацию ремонта"}>{playing?<Pause size={17} fill="currentColor"/>:<Play size={17} fill="currentColor"/>}</button><div className="timeline-main"><div className="timeline-label"><span>{scrollMode?"Листайте — квартира преображается":"Ремонт всей квартиры"}</span><span>{Math.round(compare?0:progress)}<small>%</small></span></div><Slider ref={node=>{node?.querySelector("[role=slider]")?.setAttribute("aria-label","Ход ремонта квартиры");}} className="renovation-slider" min={0} max={100} step={1} value={[compare?0:progress]} onValueChange={([v])=>setStage(v)}/><div className="timeline-milestones">{stages.map((s,i)=><button key={s.name} className={activeStage===i?"active":""} onClick={()=>setStage(s.at)}>{s.name}</button>)}</div></div><div className="timeline-extra"><button className="speed-button" onClick={()=>setSpeed(s=>s===.5?1:s===1?2:.5)} aria-label={`Скорость анимации ${speed}x. Изменить`}>{speed}×</button><button className={`compare-button ${compare?"active":""}`} onClick={()=>{setCompare(!compare);setPlaying(false);setScrollMode(false);}} aria-pressed={compare}><Layers3 size={16}/>{compare?"После ремонта":"До ремонта"}</button></div></div>
   </div>
   <div className="apartment-footnote"><span>{exportUrl?<a className="export-link" href={exportUrl} download={`gasgarick-${apartmentId}.png`}>Скачать последний кадр PNG <Download size={13}/></a>:"Демонстрационные планировки · размеры помещений условные"}</span><div className="scroll-mode-toggle"><label htmlFor="scroll-mode">Ремонт по скроллу</label><Switch id="scroll-mode" checked={scrollMode} disabled={reduced} onCheckedChange={v=>{setScrollMode(v);setPlaying(false);setTour(false);setCompare(false);if(v)selectRoom(null);}}/></div></div>
  </div>
  <Toaster position="bottom-center" theme="light"/>
 </section>;
}
